name: GIFT OF LOVE
favicon: null
layout_spectrum: 0.28711
typography_spectrum: 0.25246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.3827668037265539
  rhythmicContrast: 0.46919854218140244
purpose: []
